language: csharp
solution: ChirpAPI.sln
mono:
        -latest
os: 
        - linux
        - osx
sudo: false

script:
    - xbuild /t:Rebuild /p:Configuration=Release ChirpAPI.sln

notifications:
    email: false
    irc:
        channels:
            - "irc.fyrechat.net#vana-commits"
        skip_join: true
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} - %{author}): %{message}"
